server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/flightApp1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: corvettec-6