server:
  port: 8084
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      port: 35730

  datasource:
    url: jdbc:mysql://localhost:3306/flightApp1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: corvettec-6
